version: "3.8"

services:
  my-app:
    image: devental/containers-monitoring-app
    container_name: my-python-container
    restart: always
    environment:
      - DOCKER_HOST=tcp://host.docker.internal:2375