name: CI/CD for Docker App # Workflows

on: # Defining a trigger
  push: # After the git push command (trigger)
    branches:
      - main
      - develop
  pull_request: # After the pull request (trigger) in your own GitHub repository (Containers-monitoring-app)

jobs:
  build-and-push:
    runs-on: ubuntu-latest # Defining a runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Copying a repository (code)

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3 # Improved mechanism for faster and more efficient container assembly

      - name: Login to Docker Hub
        uses: docker/login-action@v3 # Automatic login to Docker Hub for further work
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5 # Action of building and transferring an application
        with:
          context: . # Specifies that Docker should build the container from the current folder
          file: ./Dockerfile # Uses a Docker file for building
          push: true # Push container permission in Docker Hub
          tags: devental/containers-monitoring-app:latest