name: CI/CD for Docker App # Workflows

on: # Defining a trigger
  push: # After the git push command (trigger)
    branches:
      - main
  pull_request: # After the pull request (trigger) in your own GitHub repository (Containers-monitoring-app)

jobs:
  build-and-push:
    runs-on: ubuntu-latest # Defining a runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3 # Improved mechanism for faster and more efficient container assembly.

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: devental/containers-monitoring-app:latest